version: "3"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    environment:
      - DB_HOST=db
      - DB_NAME=careerhub
      - DB_USER=postgres
      - DB_PASS=root@1234
    depends_on:
      - db
    entrypoint: /entrypoint.sh

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=careerhub
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root@1234
    ports:
      - "5433:5432"