# Generated by Django 2.2.2 on 2019-11-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
